Initial Commit
f13babylon/f13babylon pull request #365
Opened 2023-12-15 03:22 UTC by Jawnner

## About The Pull Request

![brave_qqz78JzuLr](https://github.com/f13babylon/f13babylon/assets/93478960/d1bc6031-5588-4895-8cfb-86433c719b72)

_"When the world went 'kaput,' God whispered, 'Enclave, you're up!' 🌎🗝️ #HeavenlyHandpickedLeaders"_

**A bunch of changes IN ACCORDANCE WITH the vision headed by lore team:**

- All Enclave armor for the most part more susceptible to lasers, so that BoS can gun them down even harder. However, they've gotten a really good bump in terms of radiation resistance, allowing the non-PA/Scientist roles to explore radiation hot zones like Mass Fusion much easier. Also, they've made their own armor a bit more resistant to their own signature weapons (plasma durr).

- Enclave Marine armor received an across the board upgrade, along with a slowdown nerf. Should be considered a direct upgrade of Reinforced Combat Armor, and now reflects so.

- Added crafting recipes of Enclave Combat Armor, Neostead 2000, Plasma Rifle, Plasma Pistol to both Enclave Lieutenants and Scientists. Also gave these roles advanced explosives crafting.

- Fixed the plasma caster, as per lolman's PR, where he wanted to bring the plasma caster up to 25 shots per MFC cell. 

- **#MadePlasmaGreatAgain**
Increased plasma damage across the board, as even with the recent adjustment, plasma was still outperformed by pretty much every laser weapon that was also hit-scan. Plasma now has the stopping power, with the previous wound adjustments, to actually make someone think before attempting to rush down someone wielding such a weapon. 

## Why It's Good For The Game

Enclave armor being more rad and energy/plasma resistant tracks for the faction, along with getting shit on by lasers considering the Brotherhood being their mortal enemy.

Enclave Marine Armor was barely above regular Enclave Combat Armor.

Crafting recipes are fun, stocking up armories are fun without bunker-rushing, gives Scientists something more to do. Also, this makes the Lieutenant more akin to their counterpart, the Head Scribe, in being a faction support role.

There can only be four plasma rifles (caster included) in the game at a single time without any sort of admin intervention. The rarity of the weapon should make it much better than an AER9 which you can find behind one gutsy in a random shop. While the projectiles are fast, them not being hitscan compared to lasers means they needed to hit much, much harder. The wound bonuses that the plasma projectiles have were nice, but never actually made a difference in the fight. Also the fire delay is untouched, so lasers still shoot faster and you can get gunned down quick.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: crafting recipes
tweak: armor values and plasma damage
/:cl:

2023-12-15 16:26 UTC, Stutternov commented
I expected to hate this upon first seeing it but honestly not a bad PR.

Suggestion I'd have though is actually not to give those roles explosive crafting.

Give scientists a loadout with advanced explosive crafting books on it as an option, and give the Specialists regular explosive crafting.

LTs don't really need it and giving Scientists a niche to be more useful will be helpful, especially since advanced explosive crafting allows chemical payload C4s now and craftable mortar shells. 

Although I will say this regarding plasma shots: **Most armors do not resist against plasma shot protection** - they don't call laser armor, if I remember correctly, they call _energy_ protection. Which very few armors have. I'd suggest leaving damage values for them unchanged, or at most, mild buffs by like ~2 damage rather than +5.

2023-12-15 17:13 UTC, Jawnner commented
> I expected to hate this upon first seeing it but honestly not a bad PR, opposite really.
> 
> Suggestion I'd have though is actually not to give those roles explosive crafting.
> 
> Give scientists a loadout with advanced explosive crafting books on it as an option, and give the Specialists regular explosive crafting. (This will make it in-line with other factions, like Khans who's chemists get a choice of better surgery or advanced explosives - or NCR where their LO has advanced explosives and engineers can get regular explosives.)
> 
> LTs don't really need it and giving Scientists a niche to be more useful will be helpful, especially since advanced explosive crafting allows chemical payload C4s now and craftable mortar shells.
> 
> Although I will say this regarding plasma shots: **Most armors do not resist against plasma shot protection** - they don't call laser armor, if I remember correctly, they call _energy_ protection. Which very few armors have. I'd suggest leaving damage values for them unchanged, or at most, mild buffs by like ~2 damage rather than +5.


Did a lot of testing:

Plasma Weaponry vs AER9 laser rifle - Naked, Reinforced Knight Armor (MK2 Combat Armor), Salvaged PA, and Senior Paladin T-51.

Plasma performed worse/less consistent against every armor, even naked it didn't really make much of a difference. While the wound bonus is apparent, it didn't matter much. The AER9 had the same shots to kill as the baseline plasma rifle, while having probably the best non-automatic fire delay in the game, making the TTK not even comparable. Add onto the fact that the server experiences higher Time Dilation in larger fights, plasma's speed compared to a hitscan is completely negligible. 

Mild buffs of 2 damage aren't a real difference-maker, especially considering the objective rarity of the weapon. Even with adding crafting, the amount of plasma rifles that could be in the game is still much, much lower than the laser weaponry. 

Removed explosive crafting from Admin-Only Captain and Lieutenant. Don't see the point in making advanced explosive crafting a seperate loadout for Scientist considering there can only be two of them. Engineer-Specialist loadout getting basic explosives is cool.

2023-12-15 17:31 UTC, Stutternov commented
> The AER9 had the same shots to kill as the baseline plasma rifle, while having probably the best non-automatic fire delay in the game, making the TTK not even comparable. 

Funnily this is due to how fire delay is being processed (it doesn't work, it lies to you) on certain guns vs others. Ballistics, as an example, are all locked to basically similar if not exact same fire delays. Quirked. (Actively being fixed)

As for armor protection - T-51 PA has roughly 50 energy protection, yeah. But combat armor has only 22 energy protection vs 50 laser protection.

Imo - I'd suggest, based off personal opinion, if you want to touch damage values to swap plasma from checking **energy** protection to instead check **laser** protection (like lasers do) - then basically make them no/low AP, high damage (they have no AP rn anyway, they used).

2023-12-15 19:44 UTC, Draganfrukts requested changes
All in all a pretty good PR, just these few outlined issues are a point of concern

2023-12-15 19:44 UTC, Draganfrukts commented on code/modules/projectiles/ammunition/energy/plasma.dm
> +	e_cost = 80 //25 shots
This is absurd for a weapon with infinitely printable ammo at minimal cost.

2023-12-15 19:44 UTC, Draganfrukts commented on code/modules/projectiles/projectile/beams.dm
> +	damage = 31 //fucc you normies
```suggestion
	damage = 30
```
Increments of 5 make it infinitely easier to track balance

2023-12-15 19:44 UTC, Draganfrukts commented on code/modules/projectiles/projectile/beams.dm
> +	damage = 23 //rapid fire
```suggestion
	damage = 25
```
ditto

2023-12-15 19:44 UTC, Draganfrukts commented on code/modules/projectiles/projectile/beams.dm
> +	damage = 22
```suggestion
	damage = 20
```

2023-12-15 19:44 UTC, Draganfrukts commented on code/modules/projectiles/projectile/beams.dm
> +	damage = 27
```suggestion
	damage = 25
```

2023-12-15 19:44 UTC, Draganfrukts commented on code/modules/jobs/job_types/enclave.dm
> +	H.mind.teach_crafting_recipe(/datum/crafting_recipe/plasmarifle)
There's a good reason you can't craft plasma guns that are better than the pistol. We shouldn't have mass production.

2023-12-15 19:44 UTC, Draganfrukts commented on code/modules/clothing/suits/f13factionarmor.dm
> +	armor = list("melee" = 45, "bullet" = 45, "laser" = 40, "energy" = 30, "bomb" = 50, "bio" = 60, "rad" = 40, "fire" = 60, "acid" = 20, "wound" = 20)
```suggestion
	armor = list("melee" = 45, "bullet" = 45, "laser" = 45, "energy" = 30, "bomb" = 50, "bio" = 60, "rad" = 40, "fire" = 60, "acid" = 20, "wound" = 20)
```
I would personally keep it at 45 laser since it's a mirror of CA with the slowdown change, looks good otherwise

2023-12-15 20:04 UTC, Jawnner commented on code/modules/jobs/job_types/enclave.dm
> +	H.mind.teach_crafting_recipe(/datum/crafting_recipe/plasmarifle)
Then may it be replaced with assault carbines?

2023-12-15 20:07 UTC, Jawnner commented on code/modules/jobs/job_types/enclave.dm
> +	H.mind.teach_crafting_recipe(/datum/crafting_recipe/plasmarifle)
I personally don't see the big deal considering NCR can mass produce rangemasters

2023-12-15 20:34 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/enclave.dm
> +	H.mind.teach_crafting_recipe(/datum/crafting_recipe/plasmarifle)
Using "X Faction can do it, so X faction should do it too" is a bad mindset. Rangemasters same as Plasma Rifles are OP in their own way.

2023-12-16 22:28 UTC, maaacha commented on code/modules/jobs/job_types/enclave.dm
> +	H.mind.teach_crafting_recipe(/datum/crafting_recipe/mp5sd)
no mp5 crafting thx

2023-12-16 22:28 UTC, maaacha commented on code/modules/jobs/job_types/enclave.dm
> +	H.mind.teach_crafting_recipe(/datum/crafting_recipe/mp5sd)
no mp5 crafting thx

2023-12-16 22:28 UTC, maaacha commented on code/modules/jobs/job_types/enclave.dm
> +	H.mind.teach_crafting_recipe(/datum/crafting_recipe/mp5sd)
no mp5 crafting thx

2023-12-16 22:28 UTC, maaacha commented on code/modules/jobs/job_types/enclave.dm
> +	H.mind.teach_crafting_recipe(/datum/crafting_recipe/neostead)
no neostead crafting thx

2023-12-16 22:29 UTC, maaacha commented on code/modules/projectiles/ammunition/energy/plasma.dm
> +	e_cost = 80 //25 shots
this just makes it a buffed plasma rifle. the limited fire ammo capacity with high fire rate higher damage is intentional

2023-12-22 10:56 UTC, CaputCapital commented on code/modules/projectiles/ammunition/energy/plasma.dm
> +	e_cost = 80 //25 shots
I agree, keep it at 10 shots.

2023-12-22 10:58 UTC, CaputCapital commented on code/modules/projectiles/ammunition/energy/plasma.dm
> +	e_cost = 80 //25 shots
> this just makes it a buffed plasma rifle. the limited fire ammo capacity with high fire rate higher damage is intentional and is in line with it's function in fallout nv

This is true.

2023-12-22 11:01 UTC, CaputCapital commented on code/modules/jobs/job_types/enclave.dm
> +	H.mind.teach_crafting_recipe(/datum/crafting_recipe/neostead)
> no neostead crafting thx

This I can understand. Plus I don't know why Enclave Sergeant gets the Neostead as a loadout option, it just ends up being a downgrade from the Assault Carbine and Plasma Rifle. To pick the Neostead loadout as Enclave Sergeant is to fall into a beginner's trap.

2023-12-22 11:03 UTC, CaputCapital commented on code/modules/jobs/job_types/enclave.dm
> +	H.mind.teach_crafting_recipe(/datum/crafting_recipe/plasmarifle)
> There's a good reason you can't craft plasma guns that are better than the pistol. We shouldn't have mass production.

Given Enclave's current state as a faction that's almost always obscured from the rest of the round, plasma rifle "mass production" would be pointless.

2023-12-25 08:30 UTC, closed without merging