OVERHAUL PT. 6: ASSAULT RIFLES REMADE
f13babylon/f13babylon pull request #434
Opened 2023-12-29 22:48 UTC by mazzinsanity

## About The Pull Request

## Why It's Good For The Game

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-01-02 11:21 UTC, Draganfrukts requested changes

2024-01-02 11:21 UTC, Draganfrukts commented on code/modules/projectiles/guns/ballistic/automatic.dm
> +	desc = "A fully-automatic FAL PARA battle rifle produced by FN Herstal. Intended for use by paratroopers and special forces. Chambered in 7.62mm."
```suggestion
	desc = "An uniquely powerful Pre-War FAL 50.63 battle rifle developed by FN Herstal. Fitted with a shorter barrel and a lightweight folding stock, intended to be used by paratroopers across the European Commonwealth. Chambered in 7.62mm."
```

2024-01-02 11:21 UTC, Draganfrukts commented on code/modules/projectiles/guns/ballistic/automatic.dm
> +	desc = "A fully-automatic R84 light machine gun manufactured by FN Herstal. Intended for suppressive fire. Chambered in 5.56mm."
```suggestion
	desc = "A Pre-War R84 light machine gun designed by FN Herstal and now manufactured by the NCR, commonly issued to Heavy Troopers. Intended for suppressive fire. Chambered in 5.56mm."
```

2024-01-02 11:21 UTC, Draganfrukts commented on code/modules/projectiles/guns/ballistic/automatic.dm
> +	desc = "A fully-automatic XM67 light machine gun manufactured in small numbers by Heckler & Koch. The ultimate refinement of the sniper's art. Chambered in 5.56mm."
```suggestion
	desc = "A bullpup Walther XM67 machine sniper rifle that has been designed from the ground up for non-stationary shooting, fitted with a collapsible stock, long-range scope, and reciprocating barrel. The ultimate refinement of the sniper's art. Chambered in 5.56mm."
```

2024-01-02 11:21 UTC, Draganfrukts commented on code/modules/projectiles/guns/ballistic/automatic.dm
> +	desc = "A fully-automatic Type 88 light machine gun manufactured by a Chinese industrial conglomerate. Sports a robust operating mechanism and reinforced stock. Chambered in 5mm."
```suggestion
	desc = "A Type 88 light machine gun of Chinese design, based on the original success of the Type 93 rifle. It sports a robust operating mechanism and a barrel meant to withstand extreme abuse, on top of it's improved frame. Chambered in 5mm."
```

2024-01-02 11:21 UTC, Draganfrukts commented on code/modules/projectiles/guns/ballistic/automatic.dm
> +	name = "\improper Colt Monitor"
```suggestion
	name = "heavy battle rifle"
```

2024-01-02 11:21 UTC, Draganfrukts commented on code/modules/projectiles/guns/ballistic/automatic.dm
> +	desc = "An especially modified light machine gun built on the BAR platform with an added pistol grip and a Cutts recoil compensator. This one features a West-Tek marksman scope and its receiver bear
```suggestion
	desc = "An especially modified Pre-War machine gun made for the Federal Bureau of Investigation, built on the famous BAR platform with an added pistol grip and a Cutts recoil compensator. This one has a West-Tek optical gunsight mounted to it's receiver for optimal accuracy. Chambered in 7.62mm."
```

2024-01-02 17:59 UTC, Fishpoker commented
25 DMG for 5.56 🤣🤣

2024-01-03 11:01 UTC, mazzinsanity commented
> 25 DMG for 5.56 🤣🤣

It used to be 26 DMG. This change is aimed at improving consistency by using multiples of 5 and making it easier to balance if needed further down the line

2024-01-05 05:56 UTC, HissyNays commented
Why the 10mm and 9mm nerf?

"for future ease of balance and consistency by using multiples of 5" I also really don't like this statement, this isn't ease of balance, this is limitation of balance and greatly harms or buffs guns that are meant to fire lots of bullets fast.

Most auto assault rifles having 3 rate of fire is good due to them getting closer to semi-auto guns in terms of viability but ultimately this is a bad change as you effectively made SMG's overall better option. Rather than curbing assault rifles why not buff bolt actions and semi-autos?

MP-5 now seems to be better than 10mm smg which is strange.

Jesus, I was gonna ask why are you buffing chinese LMG but then I look at previous stats and they are mad, this needs even bigger nerf to stay in line with other LMG's, primarily to slowdown.

The colt monitor nerf was definitely not needed, it has such a big slowdown that it's practicly a meme gun. If it at least had actually big magazine and good fire rate it would make sense, but now it's just an even bigger joke. No wonder I often seen heavy troopers leave colt monitors to collect dust.

Chinese LMG,  colt monitor and R84 LMG badly need to get slowdown lowered/increased at least to 1. This will create a much more fair balance.
I don't understand why chinese LMG given exclusively to legion needs to be exceptional compared to other LMG's in terms of movement speed. You shouldn't be able to effectively chase and push people with LMG.

Semi-auto rifles seem to be entirely forgotten and they are in biggest need of buffs. Marksman carbine needs a scope that is viable. Service rifle remains in lowest tier of weapons, scout carbine is just slightly better service rifle which is saved by being scopeable but still remains subpar.

2024-01-05 14:56 UTC, mazzinsanity commented
> Semi-auto rifles seem to be entirely forgotten and they are in biggest need of buffs. Marksman carbine needs a scope that is viable. Service rifle remains in lowest tier of weapons, scout carbine is just slightly better service rifle which is saved by being scopeable but still remains subpar and there's more examples if you dig.

![vince-mc-mahon-gulp](https://github.com/f13babylon/f13babylon/assets/77054674/681e5f57-f08e-4905-abed-ea13c0f5584e)

Can you guess what guns will be overhauled next?

2024-01-05 14:57 UTC, mazzinsanity commented
> MP-5 now seems to be better than 10mm smg which is strange.

The MP5 is meant to be a tier above the 10mm SMG. Same with the Uzi.

2024-01-05 14:59 UTC, mazzinsanity commented
> I don't understand why chinese LMG given exclusively to legion...

The Chinese LMG and its blueprint can now be found as High tier bunker loot. Same with the R84.

2024-01-05 22:33 UTC, Stutternov approved these changes

2024-01-05 22:33 UTC, merged

2024-01-06 03:27 UTC, HissyNays commented
> > I don't understand why chinese LMG given exclusively to legion...
> 
> The Chinese LMG and its blueprint can now be found as High tier bunker loot. Same with the R84.

Even so, there's still a large gap in slowdown between chinese lmg and other other lmg's which makes little sense. I can Imagine it still stays good for run'n'gunning but we can just wait and see how it is in game meanwhile with other LMG's you might aswell lay down and crawl instead, you won't lose much speed and force everyone to click your sprite directly, this is especially true to heavy trooper role due to SPA.