Full Enclave Base Rework
f13babylon/f13babylon pull request #443
Opened 2024-01-01 19:45 UTC by panzerr1944

## About The Pull Request
A full, complete rework of the enclave base by mashing both the existing enclave base and an old wasteland era version together into one smaller than the current one but better in every way bunker!

![image](https://github.com/f13babylon/f13babylon/assets/76122712/6525a03b-00f9-4a41-a17a-8d399adee120)

## Why It's Good For The Game
Two points of entry rather than one (mines and front, the bunker is actually flankable now holy shit), fully functional camera system, mood lighting, rooms, offices, cool holotable meeting room, remnant aesthetic, cleanable walls and grime and overall improvements to make the base more interesting to be in, attack and defend from. Spawns that are OUTSIDE offices incase one is being used for something (except le barracks for obvious reasons) and a direct mines connection.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
🆑 
add: new enclave base
add: ability to clean rusted walls
del: old enclave base
tweak: shuffles the exterior weapon spawner into the armoury
add: various maintenance loot spawners
add: extra tools + 25 concrete
add: 2 ornamental trophies (t60 helm with no armor, overcharged mfc, both anchored)
🆑

2024-01-02 17:33 UTC, BadAtThisGame302 commented
Really? Dense rock all around the base again? I thought we were over this before.

2024-01-02 18:57 UTC, panzerr1944 commented
> Really? Dense rock all around the base again? I thought we were over this before.

Two points of entry. You can mortar into it still in spite of it being underground. Compared to other bases currently on-server, this is nothing in comparison. If in game it proves too much, I'll add a third method of entry

2024-01-06 18:10 UTC, spockye requested changes
![image](https://github.com/f13babylon/f13babylon/assets/79304582/db28c8da-1eb8-4b6e-8582-7eac69d1993b)

floating lights

2024-01-08 04:00 UTC, Stutternov approved these changes

2024-01-08 04:00 UTC, merged